apiVersion: v1
kind: Pod
metadata:
  name: itvTest
spec:
  containers:
  - name: itvTest
    image: itvTest:latest
    # Just spin & wait forever
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]